### ISSUE TITLE
'우리가 하는 일' 상세 페이지 가독성을 높이는 방법을 논의합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#10]
블로그 가독성을 높이기 위한 몇가지 아이디어를 내봅니다. 
(예시 콘텐츠로는 https://parti.coop/posts/112 를 확인해주세요.)
 
- [x] 글씨 크기 
PC 버전은 괜찮은데 모바일에서 볼 때, 본문 글씨가 조금 크다고 느껴져요. 20-30대 다른 크루에게도 같은 피드백을 들었고요. 하지만 40대 이상 혹은 원시이신 분들은 어떠신지 의견 궁금합니다.   
제가 생각하는 적정 글씨 크기는 (헤드 빼고) 본문은 슬로워크 블로그(https://slowalk.tistory.com/2598) 정도 되면 괜찮지 않을까 싶어요.

- [x] 링크 
링크로 추가된 텍스트가 PC나 모바일에서 크게 도드라지지 않는데, 언더라인이나 색 추가가 되면 좋겠습니다. 

- [x] 이미지 캡션
이미지에 캡션을 넣으면 캡션이 본문보다 글씨가 조금 더 작으면 가독성이 올라갈 것 같아요. 

- [ ] 제목/부제목
지금은 제목만 메인에 드러나도록 되어있는데, 미디엄처럼 (선택으로) 부제목을 쓸 경우 드러나면 어떨까요? 
제목으로만 담지 못하는 본문 내용을 부제목이 뒷받침해줄 수 있지 않을까 하여 내놓은 아이디어 입니다.

**Comment by dalikim** [comment]
@gjkimpam 부제목은 이 이슈와 살짝 동떨어져 보여요. 혹시 다른 일감으로 만들면 어떨까해요.

**Comment by gjkimpam** [comment]
> @gjkimpam 부제목은 이 이슈와 살짝 동떨어져 보여요. 혹시 다른 일감으로 만들면 어떨까해요.

네, 좋습니다.

**Comment by gjkimpam** [comment]
@dalikim 
1. 글씨 크기
2. 링크
3. 이미지 캡션  
모두 확인했습니다. 좋습니다. 

+ 본문에서 마크다운한거 일부가 깨지는 현상이 있는데 이건 추가 이슈 만들게요.
