### ISSUE TITLE
개인정보처리방침을 수정합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#12]
https://parti.coop/privacy 

- [ ] 방침 버전 관리를 위해서 연도별 방침(1차: 201?년~2018년, 2차: 2019년, 3차: 2020년 개정판) 링크 생성합니다. 
- [ ] 변호사님에게 2020년 방침 최종 받습니다. 
- 변경 시기: 2020년 1월 후

**Comment by gjkimpam** [comment]
확인했습니다. 혹시 혜윰에 한번 검토가 필요할까요?

**Comment by dalikim** [comment]
@gjkimpam 그럴 필요없을 듯해요.

**Comment by gjkimpam** [comment]
> @gjkimpam 그럴 필요없을 듯해요.

네, 알겠습니다.
