### ISSUE TITLE
공유회 피드백

### ISSUE THREAD

**Issue by jjuwoo** [parti-coop/parti_home#125]
@zezesong @Dandi-hwang @jay-parti @sshony (@트리 님 깃헙 아이드를 못찾겠네요 ㅠ)
1. 빠띠 홈페이지에 들어갈 배너 형태
: 저는 레이어팝업이 좋습니다. 
1-1. 이벤트보기 > 행사보기 로 텍스트 변경해야겠네요.
1-2. 검정색 보더가 들어가는게 강렬해보이긴하는데 빠띠 홈페이지에 올렸을때 너무 강해보이지 않나 고민이 쪼~꼼 됩니다. 보더없이 흰색으로 깔끔하게 가도 될것 같은데.. 지나가는 의견정도로 

2. 공유회페이지
2-1. fullpage로 갈것이 아니라면 상단 키비영역의 세로값을 줄이고 첫화면에 디지털기술은 민주주의를 어떻게 혁신하고 있을까요. 부분이 더 많으 보이면 좋겠네요.
2-2. 전체 흐름이 아래와 같은데 왔다갔다 하는 느낌이 있네요... 
> 타이틀이 '디지털기술은 민주주의를 어떻게 혁신하고 있는가' 라서일반적인 이야기를 할것 같은데 내용은 빠띠 이야기이고
> 그다음 빠띠 영상이 나오고 
> 이런 이야기를 나누고 추천한다 설명이 나오고
> 장소가 나오고
> 자세한 일정이 나오고
> 빠띠 설명이

구조를 바꾸면 좋겠는데 콘텐츠를 보니 빠띠소개보다 2022행사 소개 중심으로 구성된것 같아서 아래와 같이 변경하면 어떨까 싶습니다.
> 2022 전반적인 소개 > 2022 자세한 소개 > 빠띠 소개 
구조만 봐주세요 ([목업](https://app.moqups.com/wyWKrQFIjv/view/page/a4b7e46ac))

**Comment by dalikim** [comment]
@jjuwoo 목표 경험을 뭘로 보는지가 다른 듯해요. 레이어팝업이 주는 감은 사이드 정보라는 느낌도 있고, 절대 많은 모바일 사용성도 그리 좋지 않습니다. 

공유회가 빠띠 미션을 덮어 버리는 정도로 과감하게 생각한다는 느낌을 줘보면 어떨까 싶어요. 애플 행사 시즌처럼요. 레이어팝업으로 커버되는건 아니라 생각이 들었어요.

**Comment by jjuwoo** [comment]
> @jjuwoo 목표 경험을 뭘로 보는지가 다른 듯해요. 레이어팝업이 주는 감은 사이드 정보라는 느낌도 있고, 절대 많은 모바일 유저의 사용성도 그리 좋지 않습니다.
> 
> 공유회가 빠띠 미션을 덮어 버리는 정도로 과감하게 생각한다는 느낌을 줘보면 어떨까 싶어요. 애플 행사 시즌처럼요. 레이어팝업으로 커버되는건 아니라 생각이 들었어요.

PC에서 레이어팝업이라고 모바일에서는 풀로 나올거라 모바일 사용성이 좋지 못한것으로 생각하진 않았습니다. 
그러나 목표 경험을 뭘로보는지에 따라 결정하는것 동의하기때문에 과감하게 덮어버리자로 가도 괜찮습니다.

**Comment by dongown** [comment]
@zezesong 
1. 홈페이지 배너 : 저도 처음에는 레이어팝업이 좋겠다고 제제님께 말씀드렸었어요. 그런데 달리님과 쭈님 이야기를 들어보니 더 과감한 선택도 좋겠다는 생각이 듭니다 :)

2. 공유회 페이지 : @jjuwoo 님이 잡아주신 목업구조 좋아요. 기존에는 Parti 2022 와 일반적인 이야기가 1:1처럼 느껴져서 공유회인지 애매했던 것 같아요. 세션에서 텍스트 위치를 바꾸는 방식으로 시도해보았는데 조금 약했던 것 같네요. 또한 직접적으로 참여단체를 이야기하는 것도 행사의 풍성도를 보여주기에 좋겠다는 생각이 드네요 :)

**Comment by zezesong** [comment]
@dongown @jjuwoo 
저도 흐름의 구조는 제안주신것이 좋다고 생각해요.
그런데 일시는 바로 위 비쥬얼에도 있고,
장소는 거의 zoom으로 참여하게 될것이라 사실 중요하지 않다고해서(지난번 세션에 화면공유하면서 비쥬얼 쪽 상단에서 장소빼는 것으로 수정)
 위에 적은 것과 중복으로 들어갈 필요는 없을 것 같아요.

처음에 개요에 대한 섹션을 만드려면,
기존 "이런이야기를 나눕니다"와 "이런 분께 추천드립니다"의 디자인을 버리고,
"이런 이야기를 나눕니다"의 텍스트는 앞으로
빼서 첫 섹션에 넣거나
아니면 텍스트를 새로 작성해야겠네요.

그렇게 하면
첫 섹션에 개요에 대한 텍스트와 참여 단체로 구성해서 만들 수 있을 것 같습니다.
참여단체 정보도 한번 체크해주시면 감사하겠습니다(로고를 넣어야 하겠네요)

**Comment by zezesong** [comment]
@dongown 
23일 배포 일정을 조정해야할 수도 있을것 같아요.

**Comment by zezesong** [comment]
비쥬얼에서
일시 아래나 위에
"zoom 및 오프라인 진행, 유튜브 중계"
이렇게라도 텍스트를 넣는 것은 어떨까요?

**Comment by zezesong** [comment]
비쥬얼에서
일시 아래나 위에
"zoom 및 오프라인 진행, 유튜브 중계"
이렇게라도 텍스트를 넣는 것은 어떨까요?


광화문, 유튜브에서
12/14 광화문빼자 해서 빼고(중요도 낮음)
12/17 유튜브 빼자해서 (줌 참여가 우선)빼게 되었네요
줌을 넣으면 다같이 언급해도 될거 같아요.

그러면 상단 비쥬얼과 연결되게 해서
텍스트와 참여단체 넣고
첫 섹션을 만들어 볼 수 있을 거 같아요

**Comment by dongown** [comment]
@zezesong 오른쪽 상단 일시 아래를 말씀하시는 것 맞죠? 텍스트 넣는 것 좋습니다 :)

이렇게 구성하게 될 경우, 동영상이 조금 애매해진다는 생각이 들긴 하네요.

홈페이지 초기에 방향 잡을 때는 공유회보다는 조금 더 빠띠를 보여주자는 방향으로 이야기했는데, 쉽지 않을 것 같아 공유회에 확 초점을 맞추는 편이 낫겠다 싶네요. 기존에 이야기했던 것들을 뒤엎는 제안이지만 동영상을 없애고, 아래에 있는 '더 나은 시민 주도를 위한 한 걸음 / 더 나은 거버넌스 ~' 부분을 1일차, 2일차 설명처럼 넣어보는 것은 어떨까요? 내용 구성은 이렇게 들어가는 거죠. @jjuwoo @jay-parti 의견도 들어보고 싶네요.

빠띠는 ~
Parti 2022는 ~
참여단체(함께하는 단체)
추천대상(이런 분들을 초대해요)
1일차 - 디지털로 만드는 더 나은 시민주도
(설명)
2일차 - 디지털로 만드는 더 나은 거버넌스
(설명)
타임테이블

**Comment by zezesong** [comment]
@dongown 
아예  타임테이블과 섞어서 구성하는 것은 어떨까요?
1일차 타이틀 설명 타임테이블
2일차 타이틀 설명 타임테이블
이렇게요~

저도 작업하면서 영상위치가 애매하다는 생각은 들었네요

**Comment by dongown** [comment]
@zezesong 1,2일차를 한번 보여주고 타임테이블을 하단에 배치하려 했던 것은, 전체 일정이 보이지 않으면 구성을 알지 못해서 복잡하게 생각할 가능성이 있겠다 싶었어요. 그런데 생각해보니 오른쪽 상단에 일정은 나와있으니 타임테이블과 섞는 것도 괜찮겠다 싶네요.

**Comment by jay-parti** [comment]
내용 파악에 시간이 조금 걸려서 늦게 의견 남깁니다. @dongown @zezesong @jjuwoo 

1. 저도 레이어 팝업이 좋겠다는 생각인데요. 새 창이 뜨니까 오히려 이게 뭐지? 혹은 이거구나 라는 인식을 줄 수 있지 않나 싶어서요.  조금 과감한걸 보자면 [기존 시안](https://app.zeplin.io/project/607e2856bb3157951c95bde8/screen/61bc91b163473b10aa493ef3) 중 4번 정도인것 같습니다.

2. 트리님이 말해주신 구성 제안 좋습니다. 그리고 위치가 가까운데 정보가 중복되어있으니, 타임테이블과 1,2일차 설명 합치는 것도 좋겠습니다.  
2-1.영상도 빠지면 전체적으로 빠띠 소개가 1~2줄 정도만 되는 것이라 고민이 듭니다.(하단의 빠띠가 말하는 민주주의도 삭제) 그런데 현 상황에서 공유회에 더 집중하자는 방향으로 이야기 되는 것 같은데요. 그러면 영상도 과감하게 빼는 것도 좋겠네요.
