### ISSUE TITLE
공유회 페이지의 영상이 아이폰에서 재생불가한 이슈

### ISSUE THREAD

**Issue by zezesong** [parti-coop/parti_home#128]
제가 영상을 이미지폴더에 넣고
video 태그를 써보려고 시도해봤었는데
경로설정을 못하겠더라구요.

그래서 구글 드라이브의 영상을 웹에 삽입할 수 있는 링크로 올렸더니
아이폰에서 재생이 안되네요.

**서버에 동영상을 올리고
그것을 링크할 수 있을까요?**

**Comment by zezesong** [comment]
https://github.com/parti-coop/parti_home/issues/new

이 영상입니다.

**Comment by zezesong** [comment]
아니면 트리님이
빠띠 유튜브 계정에 해당영상 올릴 예정이라고 하셨었는데
유튜브에 올려서
유튜브 링크를 넣어야할까요?

**Comment by dalikim** [comment]
네 유튜브로 진행해야 합니다.
