### ISSUE TITLE
협업문의에 마케팅 정보 제공 동의를 추가합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#13]
뉴스레터를 보낼 수 있도록 개인정보방침 동의 아래, 마케팅 정보 제공 동의 버튼을 추가했으면 합니다. 
관련한 안내 문구는 변호사님에게 초안을 받고 다듬을 예정입니다.

**Comment by gjkimpam** [comment]
- 한번에 세가지 사항을 체크할 수 있는 체크박스가 추가되면 어떨까요? 
![스크린샷 2020-02-26 오후 6 28 36](https://user-images.githubusercontent.com/35594166/75331536-3be73b00-58c6-11ea-9277-1c07c1c36b15.png)

- '마케팅 정보 수신'과 '민주주의 리포트' 밑에 설명 글이 들어가 있으니 어떤 내용인지 파악할 수 있어 좋네요. 다만 
"빠띠가 진행하는 여러 이벤트의 알림을 받으시고 혜택을 놓치지 마세요." 이 설명글은 아이콘에 마우스를 가까이 했을 때 말풍선으로 보이면 선택 항목들이 더욱 분명히 보일 것 같아요. 
![스크린샷 2020-02-26 오후 6 34 45](https://user-images.githubusercontent.com/35594166/75331804-af894800-58c6-11ea-972f-0670714ec627.png)

- bold 되어 있는 **민주주의 리포트**를 일반 굵기로 조정해주세요.

**Comment by dalikim** [comment]
1) 체크박스 추가할께요.
2) 말풍선도 좋네요. 다만 지금처럼 그냥 보이는 것도 디자인만 좀 다듬어지면 마우스를 움직일 필요도 없이 바로 보여서 좋을 듯합니다. 마우스 호버에서 말풍선 보이는 UX가 저는 경우에 따라 좋기도 나쁘기도 한걸로 압니다. 지금처럼 자주 접하지 아니하는 협업 신청에서는 말풍선 보다는 바로 보이는게 어떨까 해요.
3) 수정할께요. 나중에 이링크가 민주주의 리포트가 모인 페이지가 되면 좋겠네요.

**Comment by dalikim** [comment]
@gjkimpam 전체 동의 버튼 추가해 테스트 서버에 올려 두었습니다.

**Comment by gjkimpam** [comment]
> @gjkimpam
> 
> 1. 체크박스 추가할께요.
> 2. 말풍선도 좋네요. 다만 지금처럼 그냥 보이는 것도 디자인만 좀 다듬어지면 마우스를 움직일 필요도 없이 바로 보여서 좋을 듯합니다. 마우스 호버에서 말풍선 보이는 UX가 저는 경우에 따라 좋기도 나쁘기도 한걸로 압니다. 지금처럼 자주 접하지 아니하는 협업 신청에서는 말풍선 보다는 바로 보이는게 어떨까 해요.
> 3. 수정할께요. 나중에 이링크가 민주주의 리포트가 모인 페이지가 되면 좋겠네요.

네, 확인했습니다. 좋습니다. 3. 민주주의 리포트 이슈는 [여기 issues/22 ](https://github.com/parti-coop/parti_home/issues/22)에서 더 논의해보아요.
