### ISSUE TITLE
정기총회 공고 팝업창 

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/parti_home#134]
정기총회 공고를 위한 팝업이 필요합니다.
우선 홈페이지 글로 올려뒀습니다. https://parti.coop/posts/337
혹시 하나의 이미지 파일로 필요하시면 작업해서 드리도록 하겠습니다.
정기총회 7일 전에는 올려야 하는 상황인데, 내일 또는 못해도 수요일까지 가능할까요?

**Comment by zezesong** [comment]
@dalikim 

기존에 팝업으로 쓰던 포맷이 있을까요?
팝업이 들어가는 브랜치 하나 만들어주시면,
제가 팝업 안에 내용이나 이미지 수정하면 될 것 같습니다~

**Comment by Mee-parti** [comment]
@zezesong 님덕 분에 공고 업데이트를 월요일에 진행할 예정입니다. 급하게 요청드리게 되었는데 챙겨주셔서 고맙습니다. 잘부탁드려요.

번거롭게도 공고문에 서면총회 개최와 타운홀 결정에 대한 사항이 들어가고 수정해야 합니다. https://parti.coop/posts/337

아래와 같은 문구가 수정 또는 추가 되었어요.
- 다음과 같이 2022년 사회적협동조합 빠띠 정기총회를 서면 총회로 개최하고자 합니다.
- 빠띠 타운홀 : https://townhall.kr/m/2411
- 총회 안건 기록 : https://nuly.do/qS2u
- 총회 안건 기록을 살펴보시고, 2월 23일 (수)까지 빠띠 타운홀로 서면 결의를 부탁드립니다.
