### ISSUE TITLE
협업문의에서 솔루션 선택 영역을 수정합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#14]
- [x] 솔루션 선택(combo box)을 체크박스로 변경하여 복수의 솔루션을 선택할 수 있게 합니다. 
참고: 슬로워크 https://slowalk.co.kr/start-a-project
- [x] 어떤 솔루션을 해야할지 잘 모르겠는 분들을 위해 '기타' 항목을 추가하고 직접 입력할 수 있게 하면 좋겠어요.

**Comment by dalikim** [comment]
@gjkimpam  '기타' 항목에 대해

1. 슬로워크는 대 고객 맞춤형 서비스를 제공하는 곳인데 반해 
빠띠 미션은 그 목표와 범위가 상대적으로 명확하고, 솔루션이 준비된 조직이라 생각합니다.

2. 준비된 솔루션 이외에 다른 솔루션이 필요한 경우, 혹은 협력요청하는 사람 입장에서 범위가 애매할 경우
기타 솔루션을 옵션으로 주는 것은 좋습니다. 다만 어떤 기타 솔루션인지 적게 놔둘 필요는 없을 듯합니다. 다른 질문 항목을 통해 우리가 유추하거나 혹은 전화/메일 등으로 물어보면 합니다.

**Comment by dalikim** [comment]
@gjkimpam https://dev.parti.coop/posts/78 주소 복사 기능을 테스트 서버에 배포해 보았습니다. 검증 부탁드립니다.

**Comment by dalikim** [comment]
@gjkimpam 카톡 공유 기능은 손보지 않아도 되겠죠?

**Comment by gjkimpam** [comment]
> @gjkimpam '기타' 항목에 대해
> 
> 1. 슬로워크는 대 고객 맞춤형 서비스를 제공하는 곳인데 반해
>    빠띠 미션은 그 목표와 범위가 상대적으로 명확하고, 솔루션이 준비된 조직이라 생각합니다.
> 2. 준비된 솔루션 이외에 다른 솔루션이 필요한 경우, 혹은 협력요청하는 사람 입장에서 범위가 애매할 경우
>    기타 솔루션을 옵션으로 주는 것은 좋습니다. 다만 어떤 기타 솔루션인지 적게 놔둘 필요는 없을 듯합니다. 다른 질문 항목을 통해 우리가 유추하거나 혹은 전화/메일 등으로 물어보면 합니다.

좋습니다. 선택 영역 부분이 변경된 것도 확인했습니다.
