### ISSUE TITLE
'우리가 하는 일' 상세 페이지 블로그 공유 채널을 추가합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#15]
현재 
<img width="206" alt="스크린샷 2019-12-03 오후 10 11 13" src="https://user-images.githubusercontent.com/35594166/70094173-d9113b00-1619-11ea-9226-58ce05f71eb8.png">

앞으로 
- [ ] 카카오톡 
- [ ] URL 복사 
가 추가되었으면 합니다. 
<img width="165" alt="스크린샷 2019-12-03 오후 10 10 26" src="https://user-images.githubusercontent.com/35594166/70094150-ce56a600-1619-11ea-9298-23533bc7a920.png">

**Comment by dalikim** [comment]
@gjkimpam 
![IMG_1FA08BF0BB89-1](https://user-images.githubusercontent.com/1650024/72117126-e1366600-338f-11ea-9220-51010f1dee77.jpeg) 카카오톡 공유는 되는데요. 저만 작동하는 것일까요?

**Comment by gjkimpam** [comment]
호호.. 저는 웹에서 [post/33](https://parti.coop/posts/33) 열었을 때, 
페북, 트위터만 뜨더라고요. 다른 블로그 웹에서 열었을 때도 카톡은 안 떠요. 
![스크린샷 2020-01-10 오후 2 53 47](https://user-images.githubusercontent.com/35594166/72129306-1e631e00-33b9-11ea-9658-1d63100c80ba.png)

**Comment by dalikim** [comment]
음 카카오톡은 모바일에서만 우선 공유 가능해요. pc카카오 앱은 거의 쓰지 않고 불안정한 경우가 꽤 있는걸로 압니다

2020년 1월 10일 (금) 오후 2:55, 찐쩐 <notifications@github.com>님이 작성:

**Comment by dalikim** [comment]
@gjkimpam 카톡 공유 기능은 손보지 않아도 되겠죠?

**Comment by gjkimpam** [comment]
> @gjkimpam 카톡 공유 기능은 손보지 않아도 되겠죠?

네, 그래요~! 

업무하는 사람들은 주로 카톡을 쓸 때 PC로 접속할테니 
PC로도 카카오톡에 보낼 수 있으면 좋겠다는 생각이 있었는데요. 
이 가설을 다시 실험해보고 싶을 때 다시 이슈 열도록 할게요.
