### ISSUE TITLE
데모스 워크숍과 의제선정단을 툴킷으로 링크합니다

### ISSUE THREAD

**Issue by dalikim** [parti-coop/parti_home#31]
제이님이 아래와 같은 요청을 주셨습니다.

> 데모스팀은 어제 툴킷 2개(워크숍, 의제선정단)를 공개했는데요, 쿱 홈페이지와 연결 요청드려요.
> 현재는 솔루션에서 각 항목을 누르면 협업하기로 연결되더라구요. 쿱 페이지에서 시민제안 워크숍, 의제선정단을 클릭하면 툴킷으로 연결될 수 있게 요청드립니다. 혹시 작업하실 때 더 드려야할 정보가 있을까요?? -시민제안 워크숍 (툴킷) : https://toolkit.parti.coop/sphere/workshop.html#_1-%EC%86%8C%EA%B0%9C
> -의제선정 및 기획 (툴킷) : https://toolkit.parti.coop/sphere/agenda.html

https://union.parti.xyz/posts/32512#anchor_comment_80326

**Comment by dalikim** [comment]
급한 건 아니라면 1.2.0 마일스톤 때 함께 배포할께요.

**Comment by gjkimpam** [comment]
> 급한 건 아니라면 1.2.0 마일스톤 때 함께 배포할께요.

좋습니다.
