### ISSUE TITLE
홈페이지 '협업문의'에 등록하면 500 에러가 뜹니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#33]
협업문의(https://parti.coop/contacts/new)에 등록하면 500 에러가 뜹니다. 

![image (4)](https://user-images.githubusercontent.com/35594166/75007608-081ca780-54b9-11ea-8295-a9029ecaa046.png)

( @kimboyhood 참고하시라고 멘션해요.)

**Comment by dalikim** [comment]
스팸봇을 방지하기 위해 구글 리캡차를 도입했는데요. 설치가 완료되지 않았네요. 설치하고 보고 드릴께요.

Uncaught Error: Invalid reCAPTCHA client id: 
    at XX (recaptcha__ko.js:528)
    at Object.lS [as execute] (recaptcha__ko.js:537)
    at new:173
    at j3 (recaptcha__ko.js:522)
    at recaptcha__ko.js:532
    at Zk (recaptcha__ko.js:303)
    at Up (recaptcha__ko.js:532)
    at recaptcha__ko.js:539
    at recaptcha__ko.js:559

**Comment by dalikim** [comment]
제가 테스트할 때는 작동하네요. @gjkimpam 님 한 번 점검해 보시고 댓글 달아 주세요.

**Comment by dalikim** [comment]
@gjkimpam 확인되었을까요?

**Comment by dalikim** [comment]
@gjkimpam 확인되었는지 궁금하네요.

**Comment by gjkimpam** [comment]
> @gjkimpam 확인되었는지 궁금하네요.

확인이 많이 늦었습니다. 죄송해요. 
제가 확인했을 때도 리캡챠가 뜨고 정상적으로 협업문의에 올라가는 것을 확인했습니다.
