### ISSUE TITLE
솔루션 페이지에 영상을 추가합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#34]
데모스(, 오르그) 영상을 추가합니다. 
- [ ] '기관 민주주의 플랫폼': 영상([유투브](https://youtu.be/SjHTe-4X1mM)) 
- [ ] '이슈 커뮤니티': 영상([유투브](https://youtu.be/ScywjSqdKTA)) 추가할지 내부 논의가 더 필요하다고 해요. @kimboyhood @ssinkjung 

- 벤치마킹 페이지는 조금 더 찾아보고 댓글로 남길게요.

**Comment by dalikim** [comment]
이건 늦어지면 다음 마일스톤으로 뺄께요. @gjkimpam

**Comment by kimboyhood** [comment]
> 데모스(, 오르그) 영상을 추가합니다.
> 
> * [ ]  '기관 민주주의 플랫폼': 영상([유투브](https://youtu.be/SjHTe-4X1mM))
> * [ ]  '이슈 커뮤니티': 영상([유투브](https://youtu.be/ScywjSqdKTA)) 추가할지 내부 논의가 더 필요하다고 해요. @kimboyhood @ssinkjung
> * 벤치마킹 페이지는 조금 더 찾아보고 댓글로 남길게요.

@gjkimpam 오르그에서 논의해보았는데요. 홈페이지 전체 개편 시기(3월 중순)에 맞추어 영상도 추가하면 어떨까 해요. 오르그에서 논의해본 솔루션 페이지의 콘텐츠 구성은 다음과 같습니다. https://union.parti.xyz/posts/32991

**Comment by gjkimpam** [comment]
> 이건 늦어지면 다음 마일스톤으로 뺄께요. @gjkimpam

네, 다음으로 빼주셔도 좋을것 같아요. 홈페이지 전체 업데이트 생각해서 조금 더 벤치마킹 사례를 살펴볼게요.

**Comment by gjkimpam** [comment]
> > 데모스(, 오르그) 영상을 추가합니다.
> > 
> > * [ ]   '기관 민주주의 플랫폼': 영상([유투브](https://youtu.be/SjHTe-4X1mM))
> > * [ ]   '이슈 커뮤니티': 영상([유투브](https://youtu.be/ScywjSqdKTA)) 추가할지 내부 논의가 더 필요하다고 해요. @kimboyhood @ssinkjung
> > * 벤치마킹 페이지는 조금 더 찾아보고 댓글로 남길게요.
> 
> @gjkimpam 오르그에서 논의해보았는데요. 홈페이지 전체 개편 시기(3월 중순)에 맞추어 영상도 추가하면 어떨까 해요. 오르그에서 논의해본 솔루션 페이지의 콘텐츠 구성은 다음과 같습니다. https://union.parti.xyz/posts/32991

네, 넣게 된다니 좋네요~! 
혹시 솔루션 페이지 벤치마킹 사례 살펴보시다가 영상이 잘 들어가 있는 타 웹페이지를 보시거든 공유 부탁해요.

**Comment by gjkimpam** [comment]
당분간 영상 추가 계획이 없어서 이슈 닫도록 하겠습니다. @dalikim
