### ISSUE TITLE
우리가 하는 일에 '민주주의 랩'을 추가합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#35]
우리가 하는 일에 “민주주의 랩”을 추가합니다. 
소스: https://toolkit.parti.coop/lab.html 

배포 후, 일부 자료는 솔루션의 캠페인으로 이동합니다.   https://parti.coop/solutions/campaign

**Comment by dalikim** [comment]
- 공공데이터•알고리즘
- 민주주의 실험

이렇게 추가할께요. 민주주의 실험에 빠띠 조직 이야기도 우선 넣어봐도 어떨까 싶네요.

**Comment by gjkimpam** [comment]
> * 공공데이터•알고리즘
> * 민주주의 실험
> 
> 이렇게 추가할께요. 민주주의 실험에 빠띠 조직 이야기도 우선 넣어봐도 어떨까 싶네요.

확인했습니다. 좋아요. 이렇게 카테고리 생성 후에 분류되지 않았던 조직 이야기를 말씀하신대로 넣어봐도 좋겠네요.
