### ISSUE TITLE
게시물을 페이스북 공유하면 url이 홈페이지 첫 페이지 주소로 보이고, 게시물의 커버 이미지가 나타나지 않습니다.

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#40]
홈페이지 블로그 중 하나를 페이스북에 공유하려다 발견했어요. 
https://parti.coop/posts/150 게시물을 디버그하면 https://parti.coop/ 을 스크랩 한 것으로 보입니다. 
 
참고
* 페북 공유 디버거: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fparti.coop%2Fposts%2F150

**Comment by dalikim** [comment]
@gjkimpam 다른 이야긴데요. 이슈의 제목을 어떻게 적어야할까요? 조금만 우리끼리 커뮤니케이션에 신경쓰면 업무가 더 효과적일텐데요. 우리 서로 이슈를 발행할때 동료 입장에서 제목이 어떻게 읽힐지, 그리고 스스로도 몇 달 후에 이 이슈를 봤을때 뭔지 쉽게 떠올릴 수 있나 한번만 더 생각하면서 제목을 적어 볼까요?

**Comment by dalikim** [comment]
@gjkimpam 테스트 서버에 배포해 봤어요.

**Comment by dalikim** [comment]
아참 그리고 마일스톤도 1.2.2로 이번에 배포하려구요.

**Comment by gjkimpam** [comment]
> @gjkimpam 다른 이야긴데요. 이슈의 제목을 어떻게 적어야할까요? 조금만 우리끼리 커뮤니케이션에 신경쓰면 업무가 더 효과적일텐데요. 우리 서로 이슈를 발행할때 동료 입장에서 제목이 어떻게 읽힐지, 그리고 스스로도 몇 달 후에 이 이슈를 봤을때 뭔지 쉽게 떠올릴 수 있나 한번만 더 생각하면서 제목을 적어 볼까요?

어떻게 표현할까 하다가.. 결국 주요 단어만 기록했네요. 네, 좋아요. 제목 수정해주신 것을 참고하여 이슈를 접할 동료와 미래의 내가 이해할 수 있게 적어볼게요.

**Comment by gjkimpam** [comment]
> @gjkimpam 테스트 서버에 배포해 봤어요.

저는 /posts/91 을 [페북 디버거](https://developers.facebook.com/tools/debug/? q=https%3A%2F%2Fdev.parti.coop%2Fposts%2F91)에서 확인했을 때, 링크 이미지가 안 뜨고 경고 이미지가 떴어요. 
![스크린샷 2020-02-27 오전 10 12 12](https://user-images.githubusercontent.com/35594166/75403073-e94f6280-5949-11ea-8a83-21ce60c65cb7.png)

**Comment by dalikim** [comment]
@gjkimpam 지금은 잘 되네요. 페이스북 오류 아닐까 싶은데요. 다시 확인해보세요.

**Comment by gjkimpam** [comment]
> @gjkimpam 지금은 잘 되네요. 페이스북 오류 아닐까 싶은데요. 다시 확인해보세요.

네, 링크 미리보기 사진 보여요. 
참고로 페북 공유 디버거 페이지에서는 링크 미리보기 사진이 여전히 안 떴는데, 페이스북 테스트 페이지에 링크를 넣어보니 이미지가 떴어요.
