### ISSUE TITLE
블로그 에디터의 마크다운 기능을 개선합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#45]
마크다운(글자 굵게, 리스트, 기울임..)을 적용하고 글 저장을 하면 마크다운이 제대로 적용 안 되고 깨지는 현상을 발견했어요. 마크다운을 **글자**로 입력했을 때, 글을 저장하고 나서 ** 글자**

예를 들어, [이 블로그](https://parti.coop/posts/80)의 경우 아래와 같이 보입니다. 

- 발행된 글 
<img width="708" alt="스크린샷 2020-03-02 오후 5 35 46" src="https://user-images.githubusercontent.com/35594166/75659735-d1f7d880-5cad-11ea-92a0-31fc949a853f.png">

- 마크다운, 미리보기로 동시에 봤을 때 보이는 글 
<img width="785" alt="스크린샷 2020-03-02 오후 5 45 22" src="https://user-images.githubusercontent.com/35594166/75659748-d7552300-5cad-11ea-9f7f-a86a2f189d2d.png">

**Comment by dalikim** [comment]
@gjkimpam 관련해서 세션이 필요합니다. 아래 이야기를 해야합니다.

1. 볼드 처리 개선
2. <center> 태그는 표준이 아닙니다. 수정이 필요해요.
3. image caption에 대한 사용법
4. <br> 태그 관련

**Comment by gjkimpam** [comment]
- [x] 볼드 처리 개선
- [x] < center > 태그는 표준이 아닙니다. 수정이 필요해요.
- [x] image caption에 대한 사용법
- [x] br 태그 관련

확인했습니다. 이슈 없어요. 이미지 캡션을 잘 다듬어보죠 흐흐.

**Comment by dalikim** [comment]
그럼 캡션 / center / br 작업하는 걸로 알겠습니다.
