### ISSUE TITLE
민주주의디지털 기술 솔루션을 GNB에 더 잘 드러나게 합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/parti_home#48]
@ssinkjung 참고하시라고 태깅합니다.

**Comment by gjkimpam** [comment]
![스크린샷 2020-03-06 오후 1 40 25](https://user-images.githubusercontent.com/35594166/76053299-13d79600-5fb0-11ea-9f8a-5a69bd6c4e06.png)

메뉴에서 
- [ ] '그룹스'를 선택할 경우 '데모스X' 썸네일이 강조되고 
- [ ] '타운홀'을 선택할 경우 '캠페인즈' 썸네일이 강조됩니다. 

나머지 데모스X와 캠페인즈는 정상 작동합니다.

**Comment by dalikim** [comment]
@gjkimpam https://dev.parti.coop/solutions/soft#anchor-item-groups 그럼 이렇게 하면 어때요?

**Comment by dalikim** [comment]
@gjkimpam 테스트 완료되었다고 보고 배포할께요.
