### ISSUE TITLE
공론장, 커뮤니티팀 솔루션 페이지를 업데이트합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#54]
빠띠의 2020년 항해지도가 명확하게 드러날 수 있도록 솔루션 1차 업데이트를 합니다.  
- [ ] 공론장팀
- [ ] 커뮤니티팀

**Comment by dalikim** [comment]
(업데이트 중)

커뮤니티 솔루션

- 함께하는 일의 내용이 좀더 필요합니다.
- 커먼즈 필드 이미지와 설명이 필요합니다.

**Comment by gjkimpam** [comment]
활동가 커뮤니티 [참여하기 버튼](https://democracy-activists.parti.xyz/)을 
- 공론장 팀은 https://democracy-activists.parti.xyz/p/public-sphere
- 커뮤니티팀은 https://democracy-activists.parti.xyz/p/community
위와 같이 각각 다르게 갈 수 있을까요?

**Comment by dalikim** [comment]
> 활동가 커뮤니티 [참여하기 버튼](https://democracy-activists.parti.xyz/)을
> 
> * 공론장 팀은 https://democracy-activists.parti.xyz/p/public-sphere
> * 커뮤니티팀은 https://democracy-activists.parti.xyz/p/community
>   위와 같이 각각 다르게 갈 수 있을까요?

이름도 달리 가면 어떨까요?

커뮤니티 활동가 네트워크 참여하기
공론장 활동가 네트워크 참여하기


이렇게 배포해 볼께요.

**Comment by dalikim** [comment]
@gjkimpam 테스트서버 배포했습니다.

**Comment by dalikim** [comment]
우선 이것도 배포할께요. 내일 보시고 바로 업데이트 필요하면 전화 주셔요. @gjkimpam @kimboyhood
