### ISSUE TITLE
푸터 Copyright 연도를 수정합니다. 

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti_home#55]
푸터 카피라이트 연도를 2019에서 2020으로 수정 부탁드립니다.

**Comment by gjkimpam** [comment]
현재는 _Copyright 2019. Parti Coop. All rights reserved._ 으로 되어 있는데, 해당 라이센스의 경우 일반 회사에서 쓰는 것이고 빠띠의 라이센스는 다시 검토해보면 좋겠다는 논의가 있었어요. 라이센스 연도 수정과 함께 정리되어 업데이트되면 좋겠습니다. 

참고
- 툴킷 페이지: 본 가이드는 CC-BY-4.0 라이선스 하에 공개합니다.
- 슬로워크: 2005-2019 Slowalk, some rights reserved

**Comment by gjkimpam** [comment]
@dalikim @anne-parti @rest515  
우선은 Copyright **2020. Parti Co-op.** All rights reserved. 으로 변경하고 
라이센스 변경은 #56 에서 논의합니다.

**Comment by gjkimpam** [comment]
@dalikim Parti Coop을 Parti Co-op으로 변경 부탁드려요.

**Comment by dalikim** [comment]
> @dalikim Parti Coop을 Parti Co-op으로 변경 부탁드려요.
 
@gjkimpam  변경했습니다

**Comment by dalikim** [comment]
@gjkimpam 테스트 보드에는 업데이트가 되지 않았지만 테스트 완료한 것으로 알고 배포할께요.
