### ISSUE TITLE
'소식'의 콘텐츠 내 이미지 캡션에 링크를 적용합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#60]
소식에 마크다운으로 콘텐츠를 쓸 경우, 이미지 캡션에 링크가 걸리도록 합니다. 

예) ([이미지 출처](https://pixabay.com/images/id-2120656))라고 기재하면, "이미지 출처"가 표시되고 거기에 링크 https://pixabay.com/images/id-2120656 가 걸리게 됩니다.

**Comment by dalikim** [comment]
https://parti.coop/admin/posts/81/edit 
(https://unsplash.com/photos/iWTamkU5kiI?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on (https://unsplash.com/t/business-work?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) -마지막 사진 
https://parti.coop/admin/posts/82/edit
(출처: [빠띠 유튜브](https://www.youtube.com/watch?v=bxbFSmihTfY)) - 1번째 사진
(출처: [민주주의 서울](https://democracy.seoul.go.kr) - 2번째 사진
https://parti.coop/admin/posts/92/edit
출처 : (http://www.seouland.com/arti/PRINT/4016.html) - 3번째 사진
https://parti.coop/admin/posts/101/edit
([이미지 출처](https://pixabay.com/images/id-2120656)) - 1번째 사진
([이미지 출처)](https://pixabay.com/images/id-1302793/) - 2번째 사진
([이미지 출처](https://democracy.seoul.go.kr/front/seoulAsk/list.do)) - 3번째
([이미지 출처](https://pixabay.com/images/id-4183250/)) - 4번째
([이미지 출처](https://pixabay.com/images/id-3471611/)) - 5번째
([이미지출처](https://pixabay.com/images/id-3241114/)) -10번째(마지막)
https://parti.coop/admin/posts/120/edit
출처 [미래혁신포럼 홈페이지](http://www.seoulfif.co.kr/) - 1번째 사진
출처 [미래혁신포럼 홈페이지](http://www.seoulfif.co.kr/) - 2번째 사진
https://parti.coop/admin/posts/132/edit
([링크](https://democracy.seoul.go.kr/front/freeSuggest/view.do?sn=180216&searchUseYn=Y&searchCondition=&searchCondition2=3&searchCondition3=&searchKeyword=&sRegDateS=&sRegDateE=&sKind=M&pageIndex=1&sSuggest_divi=&suggestask_sn=&sDiscussionSn=&sPracticeSn=)) - 1번째 사진
https://parti.coop/admin/posts/151/edit
(http://toolkit.parti.coop/sphere/workshop.html#_1-%EC%86%8C%EA%B0%9C) - 1번째 사진
(http://townhall.kr/) - 4번째 이미지

**Comment by gjkimpam** [comment]
아직 테스트에 안 올라온거 맞죠? 테스트 서버에서는 아래와 같이 떠요. 
![스크린샷 2020-03-17 오전 9 36 44](https://user-images.githubusercontent.com/35594166/76810846-d639ff00-6832-11ea-8945-56ff07663b23.png)

**Comment by dalikim** [comment]
@gjkimpam 
1. 이 이슈에 마일스톤도 이번 릴리즈로 표시 안되어 있고
2. 그룹스 위키에도 없어서 진행하지 않고 있습니다.

진행해야하나요?

**Comment by gjkimpam** [comment]
> @gjkimpam
> 
> 1. 이 이슈에 마일스톤도 이번 릴리즈로 표시 안되어 있고
> 2. 그룹스 위키에도 없어서 진행하지 않고 있습니다.
> 
> 진행해야하나요?


아니요. 이번 릴리즈에 안 해도 돼요. 이렇게 댓글을 남기셔서 저도 테스트해야하나 궁금했었어요.  https://github.com/parti-coop/parti_home/issues/60#issuecomment-599617609

**Comment by gjkimpam** [comment]
이미지 캡션에 링크 거는 마크다운을 쓸 때 아래와 같이 적용되지 않은 것을 발견했어요. 
![스크린샷 2020-04-13 오후 3 20 05](https://user-images.githubusercontent.com/35594166/79097361-90714780-7d9a-11ea-82bb-b705b1775e41.png)

**Comment by dalikim** [comment]
@gjkimpam 캡션 안에서 마크다운을 적용하는 방법을 찾지 못했어요. html 문법을 적용하면 됩니다.


```
[xx](링크)
==>
<a href="링크">xx</a>
```

**Comment by gjkimpam** [comment]
네, html로 하니 되네요. 확인했습니다.
