### ISSUE TITLE
커뮤니티 솔루션 페이지의 함께하는 일 텍스트를 수정합니다.

### ISSUE THREAD

**Issue by kimboyhood** [parti-coop/parti_home#64]
- 협력 프로젝트(Collaborate)

지속가능하고 협력적인 커뮤니티를 만드는 일에 관심이 있으신가요? 빠띠의 노하우가 담긴 툴킷과 디지털 플랫폼을 기반으로 협력적 커뮤니티를 함께 만들 수 있습니다. 초기 아이디어 단계여도 좋습니다. 마음껏 프로젝트를 제안해주세요.

- 교육 및 워크숍(Inspire)

협력적 커뮤니티를 직접 디자인하고, 경험해볼 수 있는 워크숍을 진행합니다. 빠띠의 워크숍은 이론이나 기술을 배우기보다 스스로 실행하며 배우는 참여형 워크숍입니다. 규모와 환경에 따라 다 회차 커리큘럼 프로그램도 가능합니다. 

- 네트워크(Connect)

더 나은 세상을 만드는 다양한 커뮤니티 활동가들을 연결합니다. 커뮤니티를 조직하고 운영하는 것에 관심있는 사람들을 만나 경험과 영감을 나눠보세요.
커뮤니티 활동가 네트워크 참여하기(링크: https://democracy-activists.parti.xyz/p/community)

**Comment by gjkimpam** [comment]
확인했습니다. 이상 없어요.
