### ISSUE TITLE
솔루션 페이지의 툴킷 디자인을 변경합니다.

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#66]
솔루션 페이지의 툴킷이 책처럼 보이는 디자인으로 변경합니다.

**Comment by murinono** [comment]
book ui 리서치 중입니다. 해당 보드를 in progress 로 이동하려면 어떻게 해야하나요? 드래그를 해도 안되고 추가를 하려고 해도 안되네요! 알려주시면 감사하겠습니다.

**Comment by gjkimpam** [comment]
> book ui 리서치 중입니다. 해당 보드를 in progress 로 이동하려면 어떻게 해야하나요? 드래그를 해도 안되고 추가를 하려고 해도 안되네요! 알려주시면 감사하겠습니다.

오잉 뭔일일까요.. 저는 to do 보드에 있는 이슈를 마우스로 드래그앤드롭해지는데 말이죠. 우선 제가 in progress로 넣어둘게요.

**Comment by gjkimpam** [comment]
@murinono 베리님 
아니면 https://github.com/parti-coop/parti_home/issues/66 페이지의 오른쪽에서 변경하실 수도 있어요. 
![스크린샷 2020-03-23 오후 3 55 07](https://user-images.githubusercontent.com/35594166/77290088-b9179b80-6d1e-11ea-9a7a-a111ad28396c.png)

**Comment by murinono** [comment]
<img width="263" alt="스크린샷 2020-03-23 오후 4 28 59" src="https://user-images.githubusercontent.com/62530290/77292348-77d5ba80-6d23-11ea-9067-3db0abeb3e3a.png">
저는 to do 옆에 삼각형이 없는걸 보니 권한이 없나봐요~

**Comment by murinono** [comment]
<img width="702" alt="스크린샷 2020-03-23 오후 3 36 39" src="https://user-images.githubusercontent.com/62530290/77292474-b1a6c100-6d23-11ea-9010-e7ec9d3db7df.png">
<img width="160" alt="스크린샷 2020-03-23 오후 3 38 42" src="https://user-images.githubusercontent.com/62530290/77292490-b5d2de80-6d23-11ea-92cd-eaef8e37b314.png">
<img width="439" alt="스크린샷 2020-03-23 오후 3 35 27" src="https://user-images.githubusercontent.com/62530290/77292500-b8353880-6d23-11ea-9e23-d6ab9f7b47a7.png">
몇가지 찾아봤는데 모두 섬네일이 세로형이네요. 그리고 무엇보다 ㅎㅎ 섬네일이 책 표지라 책의 느낌이 나는 듯 해요. 지금 책 표지를 만들 수는 없으니 우선 세로형 섬네일 틀을 만들어볼게요

**Comment by dalikim** [comment]
@murinono 네 방금 초대 수락 확인했구, 쓰기 권한도 드렸습니다. (초대 수락하자마자는 기본 읽기 권한만 가능해요)

**Comment by murinono** [comment]
툴킷이 6개, 3개, 2개인 곳이 있어서 3열 2열짜리 넣어봤어요. 섬네일이 더 작게 들어갈 수도 있는데 서브 설명문이 좀 길어서 더 줄어들긴 어려울 것 같네요.. 서브 설명이 줄어들거나 생략되면 4열도 가능할듯 합니다. https://zpl.io/aRd9qee

**Comment by dalikim** [comment]
@murinono 수고하셨네요. 세로형 섬네일 틀을 보니 더 그런 생각이드는데요. 당장은 툴킷마다 섬네일을 만들기 무리이겠다 싶어요. 툴킷마다 변별력 높은 이미지를 계속 찾기는 부담이예요. 툴킷이 많이 만드는 시절이라 더 그렇구요.

주신 레이아웃은 훌륭하니, 이미지가 아닌 제목 등으로 대체할 수 있는 방법이 있을까요? 가급적 심플하게요.
@gjkimpam 님은 어떠세요?

**Comment by gjkimpam** [comment]
포트폴리오와 툴킷이 구분되니 좋네요. :) 
- @murinono 툴킷이 10개 이상 생기는 솔루션도 생길 예정이라 서브 설명을 줄이거나 아예 생략해서 4열 만드는 것도 좋아요. 
- @dalikim 저도 툴킷 썸네일(책 표지)을 베리님이 디자인해주시지 못할 때도 쉽게 만들 방안이 필요할 것 같아요. 베리님이 책 표지 패턴/템플릿을 만들어주시면 색깔이나 제목을 달리해서 저희가 계속 만들 수 있게 해도 좋고요.

**Comment by murinono** [comment]
https://zpl.io/aRd9qee 

* 4열 작업했습니다. 
* 표지 샘플을 최대한 간단하게 만들 수 있는 버젼으로 넣어봤는데요, 이걸 어떻게 작업해서 드려야 탬플릿을 수정해서 쓰실 수 있나요?

**Comment by murinono** [comment]
https://zpl.io/aRd9qee

@gjkimpam @dalikim 섬네일? 네모 박스 컴포넌트라고 해야할까요.. 여기에 제목과 서브 내용이 들어갈 수 있도록 작업했어요. 소식 컴포넌트와 비슷한 버젼 / 조금더 책의 느낌이 나고 컬러 변경을 준 선반 버젼

**Comment by gjkimpam** [comment]
@murinono  선반 버전은 툴킷이 어떤 주제 책의 시리즈 같아 보여 좋네요. 
소식 컴포넌트 혹은 선반 버전 중에 적용해보면 어떨까요? @dalikim 
제목, 서브 내용 글씨 크기는 dev에 올라온 것 보고 (크기를 조금 키우는) 조절해봐도 좋을 것 같아요. 

![스크린샷 2020-03-26 오전 11 38 17](https://user-images.githubusercontent.com/35594166/77604628-5577b300-6f56-11ea-82c4-c906ef2b6105.png)

**Comment by murinono** [comment]
이 이슈 클로즈 해도 될까요?
