### ISSUE TITLE
솔루션 페이지 '커뮤니티'에 '프로세스' 추가합니다.

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#67]
솔루션 > 커뮤니티 팀에 '프로세스' 카테고리가 생기고, 인포그래픽이 추가됩니다.

**Comment by murinono** [comment]
프로세스 이해 중..; 입니다. https://docs.google.com/document/d/12R9hGzbOUFNqminisG4CYfQefAQTUWQtfVwh3CdDZFk/edit?ts=5e724c4b# 질답 문서에 소년님 태그하여 질문 올림.

**Comment by dalikim** [comment]
> 프로세스 이해 중..; 입니다. https://docs.google.com/document/d/12R9hGzbOUFNqminisG4CYfQefAQTUWQtfVwh3CdDZFk/edit?ts=5e724c4b# 질답 문서에 소년님 태그하여 질문 올림.

필요하시면 @kimboyhood @ssinkjung 이레님과 미팅을 주선해 드릴까요?

**Comment by murinono** [comment]
https://zpl.io/aRd9qee 
툴킷 디자인 잡은 페이지에 프로세스 도식 넣어두었습니다. @gjkimpam 소년님께 피드백 부탁드리겠습니다!

**Comment by murinono** [comment]
https://zpl.io/aRd9qee @gjkimpam 피드백 반영 올려두었습니다~
