### ISSUE TITLE
협력적 커뮤니티 솔루션 페이지의 포트폴리오, 이미지, 서브텍스트 내용을 수정합니다.

### ISSUE THREAD

**Issue by kimboyhood** [parti-coop/parti_home#69]
- [x] 1. 포트폴리오: 쓰덕을 일인당으로 변경
- 기존: 버나크, 커먼즈필드제주, 나알당, 쓰덕
- 변경: 버나크, 커먼즈필드제주, 나알당, 일인당

- [x] 2. 이미지: 구글드라이브 이미지 중 1안을 사용합니다. https://drive.google.com/drive/folders/19JYQQ2vVBMGyisbfUeZYwvrvyWNUNQt0?usp=sharing

- [x] 3. 각 포트폴리오의 설명텍스트를 수정합니다.
- 커먼즈필드 제주: 삶의 전환을 실험하는 시민 커뮤니티
- 버터나이프크루: 성평등 정책을 만드는 청년 커뮤니티
- 일인당: 일인가구 공동공간을 만드는 지역 이슈 커뮤니티
- 나알당: 국내 최초 이슈 프로젝트 정당

**Comment by gjkimpam** [comment]
정리해주신 것 확인했고 이상없습니다.
