### ISSUE TITLE
'글 추가'에 임시저장 기능을 어떻게 마련하면 좋을까요? 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#7]
'[우리가 하는 일](https://parti.coop/what_we_do)' 콘텐츠를 발행하기 전에 **임시저장** 기능이 필요합니다. 

임시저장 기능이 필요한 이유 
- 콘텐츠 발행 전 내부 QA 
- 완성도 있는 글을 업로드

**Comment by gjkimpam** [comment]
임시저장 기능을 마련하기 전까지, 임시 방편으로 블로그 글 확인할 아이디어를 제안합니다.  

1. 발행일시를 2010년(과거)로 설정하고 블로그를 (임시)발행합니다. 
예) 2010-03-03으로 설정 https://parti.coop/posts/111
2. 발행된 링크로 콘텐츠를 확인하고, 필요한 경우 수정합니다. 
3. 발행일시를 2019-??-??으로 재설정하여 콘텐츠 최종 발행합니다.

**Comment by dalikim** [comment]
@gjkimpam 우선 발행일을 비워두면 홈이나 사용자가 보는 글 목록에선 노출되지 않게 조치해 봤어요. 확인 부탁드려요

**Comment by gjkimpam** [comment]
> @gjkimpam 우선 발행일을 비워두면 홈이나 사용자가 보는 글 목록에선 노출되지 않게 조치해 봤어요. 확인 부탁드려요

확인했습니다. 임시저장 기능은 발행 일시를 넣지 않고 글을 올리는 것으로 하면 되겠네요.
