### ISSUE TITLE
'솔루션'을 대체할 용어를 찾고 교체합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#71]
각팀의 활동/사업 영역을 소개하는 _솔루션_ 이란 단어가 이해하기 어렵다는 의견이 있어, 직관적으로 이해하기 쉬운 용어를 찾고 이를 교체합니다. 
예) 우리가 하는 일, 사업 영역, 활동 분야, 툴킷..

**Comment by gjkimpam** [comment]
GNB에 '솔루션'이 '우리가 하는 일'로 변경된 것 확인했어요. 

- 메인 페이지 첫번째 '우리가 하는 일'을 '소식'으로 변경 부탁드려요.  
![스크린샷 2020-04-13 오후 1 48 54](https://user-images.githubusercontent.com/35594166/79092965-9a407e00-7d8d-11ea-808a-9c171761b7ec.png)

**Comment by dalikim** [comment]
@gjkimpam 테스트 부탁드리고요.

개발이 필요하면 어사인을 다시 저로 넘겨주는 방식으로 서로 소통하면 어떨까요?

**Comment by gjkimpam** [comment]
> @gjkimpam 테스트 부탁드리고요.
> 
> 개발이 필요하면 어사인을 다시 저로 넘겨주는 방식으로 서로 소통하면 어떨까요?

asignee가 저로 되어있었군요. 어사이니 해제했어요. 앞으로 개발 필요할 때 달리 님 어사인 드릴게요. 
수정해주신 것도 확인했습니다.
