### ISSUE TITLE
홈페이지 협업문의시, 알림을 받을 수 있게 합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#72]
협업문의 시, 
- [x] 슬랙 parti-activists #bot-docking 알림이 오도록 설정한 것을 ➡️ parti 크루 슬랙으로 변경합니다.  
- [x] 이메일로도 알림을 받을 수 있게 합니다. 

+ @ssinkjung

**Comment by dalikim** [comment]
테스트 서버에서 협업요청하면 알림 슬랙은 #bot-테스트 채널로 쌓이게 했습니다. 알림 메일은 실제 발송되지 않고 https://dev.parti.coop/letter_opener/ 으로 쌓이게 했습니다.

**Comment by gjkimpam** [comment]
확인했습니다. 이상 없습니다.
