### ISSUE TITLE
메인 페이지 솔루션에서 공익데이터로 변경합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/parti_home#75]
메인 페이지 솔루션에 공공 공익데이터로 적혀 있습니다.
공익데이터로 부탁드립니다.

<img width="754" alt="스크린샷 2020-04-01 오후 3 25 15" src="https://user-images.githubusercontent.com/58237640/78105914-3cc33d80-742d-11ea-851c-597041b70014.png">

**Comment by gjkimpam** [comment]
@Mee-parti #65 에서 올려뒀어요. 혼선을 줄이기 위해 지우면 이 이슈는 지우면 어떨까 해요.

**Comment by Mee-parti** [comment]
네, 안그래도 제가 분명 봤는데 왜 수정이 안되었나 했습니다. 아직 손 보지 않으신 거군요.
