### ISSUE TITLE
시민주도 캠페인 페이지의 워딩,링크를 수정합니다

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/parti_home#76]
**함께 하는 일**
- [x] 캠페인 개발과 협업 -> "캠페인 기획과 협업"로 수정합니다.
- [ ] 캠페인 컨설팅과 교육 -> "캠페인 교육 워크숍"로 수정합니다.
   누구나 시민주도 캠페인 쉽게 할 수 있도록 "교육과 워크숍"을 제공합니다로 수정합니다.

**포트폴리오**
- [x] 아청법 개정을 촉구 -> "아청법 개정 촉구" 수정합니다.
- [x] "#우리에겐 페미니스트 선생님이 필요합니다"를 추가합니다.
  링크 : https://wouldyouparty.campaigns.kr/campaigns/5
- [x] "캠페이너 인생게임"를 추가합니다.
  링크 : https://parti.coop/posts/89

**Comment by gjkimpam** [comment]
확인했고 이상없습니다.
