### ISSUE TITLE
민주주의랩 페이지의 포트폴리오 구성을 수정합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/parti_home#77]
**포트폴리오**
- [x] 미래에서 온 투표는 캠페인 & 미래에서 온 투표 대선 공약발표회를 합치는 건 어떨까요? 또한 미래에서 온 투표는 캠페인에도 있어도 있어서 뺴는 건 어떨까요?
- [x] 세월호 아카이브도 데이터에도 있는데, 하나를 선택하면 어떨까요?
- [x]  하야 GO 사진 변경 https://toolkit.parti.coop/lab.html
![lg_1cf88d886b](https://user-images.githubusercontent.com/58237640/78107033-ae9c8680-742f-11ea-9663-96919ae7243f.jpg)
이건 어떨지 고민되네요. 
- [x]  GMO완전표시제 입법 청원 캠페인 / 나는 알아야 겠당을 하나로 합치면 어떨까요? 
- [x]  바글시민와글입법 1-3까지 합치면 어떨까요?

**Comment by gjkimpam** [comment]
정리해주신 것 확인했고 이상없습니다.
