### ISSUE TITLE
민주주의 랩, 공익데이터 솔루션 페이지의 키비주얼 이미지 수정합니다.  

### ISSUE THREAD

**Issue by murinono** [parti-coop/parti_home#80]

**Comment by gjkimpam** [comment]
@달리 드라이브에 파일 두개 확인하실 수 있어요. 
- 구글 드라이브(이미지 파일 유): https://drive.google.com/drive/u/0/folders/1ZBLZRXxGBiBzs9pNqd3VzU3fWVSYnRVv
