### ISSUE TITLE
협업문의에서 '협업문의하기' 버튼을 누르면 등록되지 않습니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/parti_home#92]
협업문의 이메일로 남겨주신 분이 홈페이지 협업문의 등록이 안 된다고 해서 저도 테스트해봤어요. 

[증상] '협업문의하기' 버튼을 누르면 로딩 표시가 10초 이상 지속되다 아래 안내가 뜹니다.  
<img width="570" alt="스크린샷 2020-04-18 오전 10 57 59" src="https://user-images.githubusercontent.com/35594166/79625337-8026e700-8163-11ea-8536-7d4c9874650e.png">

**Comment by dalikim** [comment]
@gjkimpam 관련해서 잠시 세션을 열어 오류 나는 화면을 보면서 원인을 살펴보면 합니다. 언제가 좋으세요?

**Comment by gjkimpam** [comment]
> @gjkimpam 관련해서 잠시 세션을 열어 오류 나는 화면을 보면서 원인을 살펴보면 합니다. 언제가 좋으세요?

1. 은희님 세션~제로 회의 사이나 2. 제로 끝나고 볼까요?

**Comment by dalikim** [comment]
제가 댓글을 놓쳤는데요. 다시 연락드릴께요.

달리ㅣ활동가
Democracy Activist Dali Kim
더 민주적인 세상, 빠띠 parti.coop
<http://partiunion.org/>


2020년 4월 21일 (화) 오후 12:15, 찐쩐 <notifications@github.com>님이 작성:

**Comment by gjkimpam** [comment]
다시 테스트해봤을 때 이상없어 닫겠습니다.
